version: '3'

services:
    php:
        image: 'akeneo/php:7.1'
        user: 'docker'
        volumes:
            - './:/srv/nelson'
            - '${SSH_AUTH_SOCK}:/ssh-agent:ro'
        working_dir: '/srv/nelson'
        environment:
            PHP_IDE_CONFIG: 'serverName=nelson-cli'
            PHP_XDEBUG_ENABLED: "${PHP_XDEBUG_ENABLED:-0}"
            XDEBUG_CONFIG: 'remote_host=172.17.0.1'
            SSH_AUTH_SOCK: '/ssh-agent'
