version: '3'

services:
    php:
        environment:
            GIT_AUTHOR_EMAIL: nelson@akeneo.com
            GIT_AUTHOR_NAME: Nelson
            GIT_COMMITTER_EMAIL: nelson@akeneo.com
            GIT_COMMITTER_NAME: Nelson
        volumes:
            - './ssh:/home/docker/.ssh:ro'
