services:
    crowdin.client:
        class: Akeneo\Crowdin\Client
        arguments:
            - '%crowdin.project%'
            - '%crowdin.key%'

    crowdin.console_logger:
        class: Akeneo\Crowdin\ConsoleLogger
        arguments:
            - '@system.translator'

    crowdin.packages.extractor:
        class: Akeneo\Archive\PackagesExtractor

    crowdin.packages.downloader:
        class: Akeneo\Crowdin\PackagesDownloader
        arguments:
            - '@crowdin.client'
            - '@event_dispatcher'

    crowdin.packages.builder:
        public: true
        class: Akeneo\Crowdin\PackagesBuilder
        arguments:
            - '@crowdin.client'

    crowdin.translation_files.updater:
        class: Akeneo\Crowdin\TranslationFilesUpdater
        arguments:
            - '@crowdin.client'
            - '@event_dispatcher'
            - '@nelson.target_resolver'

    crowdin.translation_files.directories_creator:
        class: Akeneo\Crowdin\TranslationDirectoriesCreator
        arguments:
            - '@crowdin.client'
            - '@event_dispatcher'
            - '@nelson.target_resolver'

    crowdin.translation_files.files_creator:
        class: Akeneo\Crowdin\TranslationFilesCreator
        arguments:
            - '@crowdin.client'
            - '@event_dispatcher'
            - '@nelson.target_resolver'

    crowdin.translation_files.project_info:
        class: Akeneo\Crowdin\TranslationProjectInfo
        arguments:
            - '@crowdin.client'
            - '@logger'

    crowdin.translated_progress.selector:
        public: true
        class: Akeneo\Crowdin\TranslatedProgressSelector
        arguments:
            - '@crowdin.client'
            - '@event_dispatcher'
            - '%crowdin.min_translated_progress%'
            - '%crowdin.folders%'
            - '%github.branches%'
