services:
    logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments:
            - '%nelson.log_file%'
            - 200

    logger:
        public: true
        class: Monolog\Logger
        arguments:
            - 'nelson'
            - ['@logger.handler']

    console_logger:
        public: true
        class: Monolog\Logger
        arguments:
            - 'nelson'

    event_dispatcher:
        public: true
        class: Symfony\Component\EventDispatcher\EventDispatcher

    system.executor:
        class: Akeneo\System\Executor
        arguments:
            - '@logger'
            - '%nelson.log_file%'

    system.translator:
        class: Akeneo\System\Translator
        arguments:
            - '%nelson.log_locale%'

    Akeneo\Command\InfoTranslatedProgressCommand:
        arguments:
            - '@crowdin.translated_progress.selector'
        tags:
            - { name: 'console.command', command: 'nelson:info-translated-progress' }
