services:
    logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments:
            - '%nelson.log_file%'
            - 200

    logger:
        class: Monolog\Logger
        arguments:
            - 'nelson'
            - ['@logger.handler']

    console_logger:
        class: Monolog\Logger
        arguments:
            - 'nelson'

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    system.executor:
        class: Akeneo\System\Executor
        arguments:
            - '@logger'
            - '%nelson.log_file%'

    system.translator:
        class: Akeneo\System\Translator
        arguments:
            - '%nelson.log_locale%'

    Akeneo\Command\InfoTranslatedProgressCommand:
        class: Akeneo\Command\InfoTranslatedProgressCommand
        arguments:
            - '@crowdin.translated_progress.selector'

    Akeneo\Command\PullTranslationsCommand:
        class: Akeneo\Command\PullTranslationsCommand
        arguments:
            - '@nelson.pull_translations_executor'
            - '@event_dispatcher'
            - '@nelson.console_logger'
            - '@github.console_logger'
            - '@crowdin.console_logger'
            - '%crowdin.download%'
            - '%github.branches%'

    Akeneo\Command\PushTranslationKeysCommand:
        class: Akeneo\Command\PushTranslationKeysCommand
        arguments:
            - '@nelson.push_translation_keys_executor'
            - '@event_dispatcher'
            - '@nelson.console_logger'
            - '@github.console_logger'
            - '@crowdin.console_logger'
            - '%crowdin.upload%'
            - '%github.branches%'

    Akeneo\Command\RefreshPackagesCommand:
        class: Akeneo\Command\RefreshPackagesCommand
        arguments:
            - '@crowdin.packages.builder'
            - '@logger'
