github:
    token: 9cb81cdeb476d72d1df01b1ffcbcadef68d25969
    fork_owner: nelson-akeneo
    owner: akeneo
    repository: pim-community-dev
    branches: ['2.3']

crowdin:
    project: akeneo
    key: 0c068ffc72bbdc6f22d7c893f26ded11
    min_translated_progress: 80
    download:
        base_dir: /tmp/crowdin-download
        locale_map: 
          pt-PT: pt_PT
          pt-BR: pt_BR
          en-NZ: en_NZ
          en_GB: en_GB
    folders: ['PimCommunity', 'AkeneoCommunity']
    upload:
        base_dir: /tmp/crowdin-upload

nelson:
    finder_options:
        in: 'src/'
        notPath: '/Oro/'
        path: '/Resources\/translations/'
        name: '*.en.yml'
    target_rules:
        '/Resources/translations': ''
        'src/Pim/Bundle': 'PimCommunity'
        'src/Akeneo/Bundle': 'AkeneoCommunity'
    pattern_suffix: 'Community'

